会場を株式会社インプレスに変更した
matsui0412/ichiyasaGitSample pull request #1
Opened 2024-06-06 05:29 UTC by matsui0412

### 変更内容
イベント開催会場を「株式会社インプレス」に更新しました。

### 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2024-06-06 05:31 UTC, yasuda-s23016 commented
文章が冷たい。200字以上書いてください

2024-06-06 05:32 UTC, Im1337xd reviewed
新しいメンバーにも分かるように、もう少し詳しい説明を書いていただけますか？:(

2024-06-06 05:34 UTC, Hyogo23014 commented
わだあつきです

2024-06-06 05:40 UTC, matsui0412 commented
> 新しいメンバーにも分かるように、もう少し詳しい説明を書いていただけますか？:(

しっかり読んでください

2024-06-06 05:40 UTC, matsui0412 commented
> 文章が冷たい。200字以上書いてください

これでせいいっぱいです

2024-06-06 05:44 UTC, Im1337xd commented
> > 新しいメンバーにも分かるように、もう少し詳しい説明を書いていただけますか？:(
> 
> しっかり読んでください

なんだろう、どんな人が見ても分かりやすい説明を記載できない人はインターネットを使うのは難しい...
![hiroyuki](https://github.com/matsui0412/ichiyasaGitSample/assets/171759726/56d809ae-00a5-4409-b7ec-48c90fdfe8a8)

2024-06-12 02:35 UTC, matsui0412 reviewed
おｋ

2024-06-12 02:35 UTC, matsui0412 commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
株式会社インプレスに修正

2024-06-12 02:36 UTC, Hyogo23014 requested changes
ふうまのこたろう

2024-06-12 02:36 UTC, Hyogo23014 commented on index.html
>                          <h3>スピーカー</h3>
「株式会社ぴーぴ」に正しい表記にしていただけますか？

2024-06-12 02:39 UTC, sunaga0 commented on index.html
>                          <p>3月23日 19:00開始</p>
３月２３日よていあるからむり！

2024-06-12 02:49 UTC, Im1337xd requested changes
🖕🏻😄🖕🏻

2024-06-12 02:49 UTC, Im1337xd commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
これってペーパーカンパニーですよね？

2024-06-12 03:31 UTC, merged